# Generated by Django 5.1.1 on 2024-10-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporting_date", models.DateField()),
                ("entity_id", models.IntegerField(default=0)),
                ("insurance_contract_id", models.CharField(max_length=100)),
                ("endorsement_type_cd", models.IntegerField(default=0)),
                ("issue_dt", models.DateField()),
                ("product_line_id", models.CharField(max_length=10)),
                ("product_id", models.CharField(max_length=20)),
                ("cohort_id", models.CharField(max_length=20)),
                ("cedeg_flg", models.CharField(max_length=20)),
                ("insurance_type", models.CharField(max_length=20)),
                ("reins_prop_cover_flg", models.CharField(max_length=20)),
                ("reins_treaty_flg", models.CharField(max_length=20)),
                ("endorsement_dt", models.DateField()),
                ("interco_cd", models.CharField(max_length=20)),
                ("interco_flg", models.CharField(max_length=20)),
                ("branch_cd", models.CharField(max_length=20)),
                ("channel_cd", models.CharField(max_length=20)),
                ("approach_cd", models.CharField(max_length=20)),
                ("transition_reporting_approach_cd", models.CharField(max_length=20)),
                ("begin_cov_dt", models.DateField()),
                ("end_cov_dt", models.DateField()),
                ("currency_cd", models.CharField(max_length=20)),
                ("prem_amt", models.BigIntegerField(default=0)),
                ("commision_amt", models.IntegerField(default=0)),
                ("pd", models.IntegerField(default=0)),
                ("lgd", models.IntegerField(default=0)),
                ("profitability", models.CharField(max_length=20)),
                ("periode_pembayaran", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Pattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periode", models.IntegerField(default=0)),
                ("claim_payment_pattern", models.FloatField(default=0.0)),
                ("claim_incurred_pattern", models.FloatField(default=0.0)),
                ("premium_payment_pattern", models.FloatField(default=0.0)),
                ("month_1", models.FloatField(default=0.0)),
                ("month_2", models.FloatField(default=0.0)),
                ("month_3", models.FloatField(default=0.0)),
                ("month_4", models.FloatField(default=0.0)),
                ("month_5", models.FloatField(default=0.0)),
                ("month_6", models.FloatField(default=0.0)),
                ("month_7", models.FloatField(default=0.0)),
                ("month_8", models.FloatField(default=0.0)),
                ("month_9", models.FloatField(default=0.0)),
                ("month_10", models.FloatField(default=0.0)),
                ("month_11", models.FloatField(default=0.0)),
                ("month_12", models.FloatField(default=0.0)),
            ],
        ),
    ]
